# Generated by Django 4.1.2 on 2023-05-20 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_user_alter_analysis_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='patients',
        ),
        migrations.AlterField(
            model_name='analysisinpatient',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysises', to='app.analysis'),
        ),
        migrations.AlterField(
            model_name='patientinorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='app.order'),
        ),
    ]
