# Generated by Django 4.1.2 on 2023-05-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order_audio_comment_alter_patient_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='audio_comment',
            field=models.FileField(blank=True, default=None, help_text='Аудио комментарий', null=True, upload_to='audio/%Y/%m/%d/'),
        ),
    ]
