# Generated by Django 4.1.2 on 2023-05-23 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_order_audio_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='audio_comment',
        ),
    ]
