# Generated by Django 4.1.2 on 2023-05-20 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_order_patients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisinpatient',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.analysis'),
        ),
        migrations.AlterField(
            model_name='analysisinpatient',
            name='patient_in_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysises', to='app.patientinorder'),
        ),
        migrations.AlterUniqueTogether(
            name='analysisinpatient',
            unique_together={('patient_in_order', 'analysis')},
        ),
        migrations.AlterUniqueTogether(
            name='patientinorder',
            unique_together={('patient', 'order')},
        ),
    ]
