# Generated by Django 4.1.2 on 2023-05-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_analysisinpatient_analysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='audio_comment',
            field=models.FileField(blank=True, default=True, help_text='Аудио комментарий', null=True, upload_to='audio/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, default=None, help_text='Изображение профиля', null=True, upload_to='patients/%Y/%m/%d/'),
        ),
    ]
